server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
#      default-filters:
#        - TokenRelay
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
        - id: cards-service
          uri: lb://cards-service
          predicates:
            - Path=/cards/**
        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/transactions/**
        - id: keycloak-login
          uri: http://localhost:8082/realms/digital-money/protocol/openid-connect/token
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1
        - id: keycloak-logout
          uri: http://localhost:8082/realms/digital-money/protocol/openid-connect/token
          predicates:
            - Path=/logout/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/digital-money
          jwk-set-uri: http://localhost:8082/realms/digital-money/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: user-service
      principal-attribute: preferred_username

